name: soft_icon_gen
description: An icon font generator for Flutter applications.
version: 1.0.0
repository: https://github.com/softyesti/soft_icon_gen
homepage: https://softyes.com.br

environment:
  sdk: ^3.5.1

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
